@startuml
|Пациент|
start
:Просмотр расписания врача;
if (Дата и время устраивает?) then (да)
    :Выбор ячейки записи;
    |Система|
    :Проверка записей пользователя;
    if (Нет записей на это же время?) then (да)
        :Отображение подробностей записи;
        |Пациент|
        :Подтверждение записи;
        |Система|
        :Выполнение записи на прием;
        :Обновление списка записей пациента;
        :Обновление расписания врача;
    else (нет)
        :Сообщение о пересечении записей;
        end
    endif
else (нет)
    :Выход из процесса;
    end
endif
stop

@enduml
